### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by notshi** [bradford-coderdojo/bltm#1]
Can we have an alternative logo to use?

**Comment by lholmes195** [comment]
We could try different services to form different styles of logos and then choose one overall

**Comment by LazyAssassin445** [comment]
I'm making a new one, what kind of style?

**Comment by notshi** [comment]
The current one looks cool, maybe something that might set the look of the game?

**Comment by lholmes195** [comment]
What do you use to make logos?

**Comment by LazyAssassin445** [comment]
cooltext.com
