### ISSUE TITLE
Game Character Images aka. Bacon Lettuce

### ISSUE THREAD

**Issue by lholmes195** [bradford-coderdojo/bltm#2]
I am just wondering whether we'd prefer the character images un-pixelised. For Example: Bacon, Tomato and Lettuce. I have software that can em able transparency and change or take out what colours are in it.

Luke.

**Comment by benwyatt2** [comment]
The in game sprites aren't images, they are a sequence of instructions that are read then the program draws the image. It would take days to write a high resolution image, so it's easier to use pixely images as they're easy to write. Use a full stop . for a transparent pixel. If you want to use shades of transparency then you have to write your own palette.

**Comment by lholmes195** [comment]
It is better to form a high resolution or medium resolution sprite than a pixel used one. You don't see top trending games with pixelised sprites.

**Comment by benwyatt2** [comment]
If you want to you can, but I tried increasing the resolution from 8x8 to 16x16 and even that completely broke the game so I had to change my sprites back to 8x8

**Comment by benwyatt2** [comment]
If it was image based then the resolutions would be much higher, but as we have to write the images in text it can be very tedious so it's better to use low resolution

**Comment by LazyAssassin445** [comment]
@benwyatt2 is right, it will be easier and look better if we use the pixelised ones, the game will also look better as it fits with the styles of the level and background

**Comment by lholmes195** [comment]
Yes, but the Pixelised images will have to fit with the game background .etc

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by benwyatt2** [comment]
The game background is already pixelised in the template Kriss and Shi gave us, as it's our first project I don't think we should stretch things too far. As we progress with projects we can make things more complex.
