### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Tommytalk52** [bradford-coderdojo/bltm#5]
Tried booting my game. Keeps crashing. We don't know why!

**Comment by hummypkg** [comment]
We've downloaded gamecake.exe and are trying to run Tom's program via a command prompt. The window opens, shows boot messages and then disappears. Is there a way to see any error messages to find the problem with his code?

**Comment by hummypkg** [comment]
We found the problem, it was a capital L in the middle of a word so there was a mismatch between graphics{} and legend{}

**Comment by xriss** [comment]
When running on windows, adding --console to the command line will keep the console open and print out debug (by default gamecake will close its console when it opens a display window)

`gamecake.exe filename.fun.lua --console`

Would be the recommended way to run on windows so you can see any errors generated.
